pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount: [ /drone/.gradle, /drone/.m2 ]
    volumes: /tmp/cache:/cache

  build:
    image: java:openjdk-8
    environment:
      - M2_HOME=/drone/.m2
      - MAVEN_HOME=/drone/.m2
      - GRADLE_USER_HOME=/drone/.gradle
    commands:
      - ./gradlew test
  
  report:
    image: eisenxu/junit-reportor
    when: 
      status: [ success, failure ]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount: [ /drone/.gradle, /drone/.m2 ]
    volumes: /tmp/cache:/cache

  notify:
    image: eisenxu/evaluation-notifier
    token: ${TOKEN}
    host: ${HOST}
    when:
      status: [ success, failure ]
