pipeline:
  build:
    image: java:openjdk-8
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew test
      - ./gradlew bootRun &
      - sleep 20
      - curl http://localhost:8080
  notify:
    image: eisenxu/drone-ketsu-notification
    token: ${EXAM_ADMIN_TOKEN}
    host: https://ketsu-backend.herokuapp.com
    when:
      status: [ success, failure ]
