freeze_files:
    - meta.yml
    - gradle/
    - gradlew
    - gradlew.bat
    - src/test/
    - .drone.yml
    - build.gradle
    - .report.json
report_files:
    - TEST-hello.IndexControllerTest.xml
    - TEST-hello.GreetingControllerTest.xml
report_target: .report.json
