freeze_files:
    - meta.yml
    - gradle/
    - gradlew
    - gradlew.bat
    - src/test/
    - .drone.yml
report_files:
    - TEST-hello.IndexControllerTest.xml
    - TEST-hello.GreetingControllerTest.xml
